# Generated by Django 6.0.3 on 2026-05-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
