# Generated by Django 6.0.3 on 2026-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_task_created_at_task_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
